FROM node:20-alpine

RUN pnpm add -g pnpm

RUN apk add --no-cache python3 build-base

RUN npm install -g pnpm@9

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
