// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUser = process.env.DB_USER || process.env.POSTGRES_USER || "postgres";
const dbPassword = process.env.DB_PASSWORD || process.env.POSTGRES_PASSWORD || "postgres";
const dbHost = process.env.DB_HOST || "db";
const dbPort = process.env.DB_PORT || "5432";
const dbName = process.env.DB_NAME || process.env.POSTGRES_DB || "jpeg_db";

const databaseUrl =
  process.env.DATABASE_URL ||
  `postgresql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbName}?schema=public`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
